server:
  port: 8092

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/plazoleta
    username: postgres
    password: 123.ayala
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
appDescription: "Pragma Powerup"
appVersion: "1.0.0"
